/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiConfigRouteImport } from './routes/api/config'
import { Route as ApiDownloadRouteImport } from './routes/api/download'
import { Route as ApiJobsRouteImport } from './routes/api/jobs'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConfigRoute = ApiConfigRouteImport.update({
  id: '/api/config',
  path: '/api/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDownloadRoute = ApiDownloadRouteImport.update({
  id: '/api/download',
  path: '/api/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsRoute = ApiJobsRouteImport.update({
  id: '/api/jobs',
  path: '/api/jobs',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/config': typeof ApiConfigRoute
  '/api/download': typeof ApiDownloadRoute
  '/api/jobs': typeof ApiJobsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/config': typeof ApiConfigRoute
  '/api/download': typeof ApiDownloadRoute
  '/api/jobs': typeof ApiJobsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/config': typeof ApiConfigRoute
  '/api/download': typeof ApiDownloadRoute
  '/api/jobs': typeof ApiJobsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/config' | '/api/download' | '/api/jobs'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/config' | '/api/download' | '/api/jobs'
  id: '__root__' | '/' | '/api/config' | '/api/download' | '/api/jobs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiConfigRoute: typeof ApiConfigRoute
  ApiDownloadRoute: typeof ApiDownloadRoute
  ApiJobsRoute: typeof ApiJobsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/config': {
      id: '/api/config'
      path: '/api/config'
      fullPath: '/api/config'
      preLoaderRoute: typeof ApiConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/download': {
      id: '/api/download'
      path: '/api/download'
      fullPath: '/api/download'
      preLoaderRoute: typeof ApiDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs': {
      id: '/api/jobs'
      path: '/api/jobs'
      fullPath: '/api/jobs'
      preLoaderRoute: typeof ApiJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiConfigRoute: ApiConfigRoute,
  ApiDownloadRoute: ApiDownloadRoute,
  ApiJobsRoute: ApiJobsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
